# Generated by Django 6.0.3 on 2026-03-26 19:44

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(
                        blank=True,
                        help_text="What problem did this solve? What did you learn?",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend API"),
                            ("automation", "Automation / n8n"),
                            ("system", "System Design"),
                            ("ai", "AI / ML"),
                            ("tool", "Developer Tool"),
                            ("other", "Other"),
                        ],
                        default="backend",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="project_thumbnails/%Y/"
                    ),
                ),
                ("screenshots", models.JSONField(blank=True, default=list)),
                ("tech_stack", models.JSONField(default=list)),
                ("features", models.JSONField(default=list)),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                (
                    "blog_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the blog post explaining how you built this.",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower = shows first in list."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-is_featured", "order", "-created_at"],
            },
        ),
    ]
