# Generated by Django 6.0.3 on 2026-03-27 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local", "Local File System"),
                            ("cloudinary", "Cloudinary Cloud Storage"),
                        ],
                        default="local",
                        help_text="Choose where to store uploaded media files",
                        max_length=20,
                    ),
                ),
                ("cloudinary_cloud_name", models.CharField(blank=True, max_length=200)),
                ("cloudinary_api_key", models.CharField(blank=True, max_length=200)),
                ("cloudinary_api_secret", models.CharField(blank=True, max_length=200)),
                (
                    "max_upload_size_mb",
                    models.PositiveIntegerField(
                        default=10, help_text="Maximum file upload size in MB"
                    ),
                ),
                (
                    "allowed_image_formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Allowed image formats: ["jpg", "png", "webp"]',
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storage_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Setting",
                "verbose_name_plural": "Storage Settings",
                "db_table": "storage_settings",
            },
        ),
        migrations.CreateModel(
            name="SystemMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("new_blog_posts", models.PositiveIntegerField(default=0)),
                ("new_subscribers", models.PositiveIntegerField(default=0)),
                ("new_contacts", models.PositiveIntegerField(default=0)),
                ("total_storage_mb", models.FloatField(default=0.0)),
                ("total_media_files", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_metrics",
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["-date"], name="idx_metrics_date")],
            },
        ),
    ]
