# Generated by Django 6.0.3 on 2026-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("company", models.CharField(blank=True, max_length=100)),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        help_text='e.g. $1,000–$5,000 or "Open to discuss"',
                        max_length=50,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        help_text="Backend API, System Design, Automation, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Private notes — not visible to sender."
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "contact_messages",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
