# Generated by Django 6.0.3 on 2026-03-27 07:16

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("bn", "Bangla")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short description for blog cards and meta description (max 300 chars).",
                        max_length=300,
                    ),
                ),
                (
                    "cover_image",
                    imagekit.models.fields.ProcessedImageField(
                        help_text="Upload 1920×1080px. Auto-converted to WebP.",
                        upload_to="blog_covers/%Y/%m/",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Google shows ~60 chars. Leave blank to use post title.",
                        max_length=60,
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        help_text="Google shows ~160 chars. Leave blank to use excerpt.",
                        max_length=160,
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated: redis, caching, django, backend",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="If this is a republished post, put the original URL here.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set a future date/time to schedule publishing.",
                        null=True,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "featured_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lower number = appears first in featured list.",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "read_time",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Auto-calculated from content length (minutes).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blogs",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown Text"),
                            ("image", "Image Block"),
                            ("code", "Code Block"),
                            ("ad", "Advertisement"),
                            ("callout", "Callout / Note"),
                            ("divider", "Section Divider"),
                        ],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lower = appears earlier. Drag to reorder in admin.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Markdown content. Use # headings, ```python code blocks, | tables |.",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True, null=True, upload_to="blog_sections/%Y/%m/"
                    ),
                ),
                ("image_caption", models.CharField(blank=True, max_length=300)),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility and SEO image indexing.",
                        max_length=200,
                    ),
                ),
                (
                    "code_language",
                    models.CharField(
                        blank=True,
                        help_text="python, javascript, sql, bash, go, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "code_filename",
                    models.CharField(
                        blank=True,
                        help_text="Optional filename shown above the code block.",
                        max_length=100,
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("adsense", "Google AdSense"),
                            ("affiliate", "Affiliate"),
                            ("custom", "Custom HTML"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ad_slot_id",
                    models.CharField(
                        blank=True,
                        help_text="Google AdSense data-ad-slot value.",
                        max_length=100,
                    ),
                ),
                (
                    "ad_custom_html",
                    models.TextField(
                        blank=True,
                        help_text="Custom ad HTML (affiliate banners, etc.).",
                    ),
                ),
                (
                    "callout_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("info", "ℹ️ Info"),
                            ("tip", "💡 Tip"),
                            ("warning", "⚠️ Warning"),
                            ("danger", "🚨 Danger"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "blog_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown on category page — describe what this topic covers.",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Hex color for the category badge/chip in the UI.",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji icon, e.g. ⚙️ 🤖 📊", max_length=10
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in nav. Lower = first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
    ]
