# Generated by Django 6.0.3 on 2026-03-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogsection",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="blog.category",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="blog.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["status", "published_at"], name="idx_blog_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["language", "status"], name="idx_blog_language"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["slug"], name="idx_blog_slug"),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["is_featured", "status"], name="idx_blog_featured"
            ),
        ),
    ]
