# Generated by Django 6.0.3 on 2026-03-27 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_key",
                    models.CharField(
                        help_text="Reference key used in API, e.g. 'mid-content-1'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("adsense_auto", "AdSense Auto Ads"),
                            ("adsense_display", "AdSense Display"),
                            ("adsense_in_article", "AdSense In-Article"),
                            ("adsense_in_feed", "AdSense In-Feed"),
                            ("custom_html", "Custom HTML Banner"),
                            ("affiliate_banner", "Affiliate Banner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("header", "Above Header"),
                            ("after_intro", "After Introduction (Section 2)"),
                            ("mid_content", "Mid Content"),
                            ("before_conclusion", "Before Conclusion"),
                            ("sidebar", "Sidebar"),
                            ("footer", "Footer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "adsense_publisher_id",
                    models.CharField(
                        blank=True, help_text="ca-pub-XXXXXXXXXXXXXXXX", max_length=100
                    ),
                ),
                (
                    "adsense_slot_id",
                    models.CharField(
                        blank=True,
                        help_text="Your AdSense data-ad-slot ID",
                        max_length=50,
                    ),
                ),
                (
                    "adsense_format",
                    models.CharField(
                        blank=True,
                        default="auto",
                        help_text="auto, rectangle, vertical, horizontal",
                        max_length=30,
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ad_slots",
                "ordering": ["placement"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name, e.g. 'Hostinger VPS'", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in /go/<slug>/ redirect URL", unique=True
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        help_text="The actual affiliate URL with your tracking ID"
                    ),
                ),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("conversion_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_earnings_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Manually update from your affiliate dashboard",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_links",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "db_table": "affiliate_links",
                "ordering": ["-click_count"],
            },
        ),
        migrations.CreateModel(
            name="RevenueEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("adsense", "Google AdSense"),
                            ("affiliate", "Affiliate Commission"),
                            ("sponsor", "Sponsorship"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=300)),
                ("event_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_events",
                        to="monetization.affiliatelink",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_events",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "db_table": "revenue_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateLinkClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(max_length=64)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="monetization.affiliatelink",
                    ),
                ),
            ],
            options={
                "db_table": "affiliate_clicks",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["link", "-clicked_at"], name="idx_aff_click_link"
                    ),
                    models.Index(fields=["-clicked_at"], name="idx_aff_click_date"),
                ],
            },
        ),
    ]
