# Generated by Django 6.0.3 on 2026-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("active", "Active"),
                            ("inactive", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
