# Generated by Django 6.0.3 on 2026-03-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("session_date", models.DateField(db_index=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("page_views", models.PositiveIntegerField(default=1)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                        ],
                        default="desktop",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                (
                    "country_code",
                    models.CharField(blank=True, db_index=True, max_length=2),
                ),
            ],
            options={
                "db_table": "visitor_sessions",
                "ordering": ["-session_date", "-last_seen"],
                "indexes": [
                    models.Index(fields=["-session_date"], name="idx_session_date"),
                    models.Index(
                        fields=["ip_hash", "-session_date"], name="idx_session_visitor"
                    ),
                ],
                "unique_together": {("ip_hash", "session_date")},
            },
        ),
        migrations.CreateModel(
            name="BlogView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                (
                    "utm_source",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("scroll_depth_percent", models.PositiveSmallIntegerField(default=0)),
                (
                    "country_code",
                    models.CharField(blank=True, db_index=True, max_length=2),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_records",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "db_table": "blog_views",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["blog", "-viewed_at"], name="idx_view_blog_date"
                    ),
                    models.Index(fields=["ip_hash", "blog"], name="idx_view_dedup"),
                    models.Index(
                        fields=["utm_source", "utm_medium"], name="idx_view_utm"
                    ),
                    models.Index(fields=["-viewed_at"], name="idx_view_recent"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HourlyBlogStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField(db_index=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("avg_time_spent", models.PositiveIntegerField(default=0)),
                ("avg_scroll_depth", models.PositiveSmallIntegerField(default=0)),
                ("top_source", models.CharField(blank=True, max_length=100)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_stats",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "db_table": "hourly_blog_stats",
                "ordering": ["-hour"],
                "indexes": [
                    models.Index(fields=["-hour"], name="idx_hourly_stat_hour"),
                    models.Index(fields=["blog", "-hour"], name="idx_hourly_blog_hour"),
                ],
                "unique_together": {("blog", "hour")},
            },
        ),
        migrations.CreateModel(
            name="PopularContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("today", "Today"),
                            ("week", "This Week"),
                            ("month", "This Month"),
                            ("all_time", "All Time"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("view_count", models.PositiveIntegerField()),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity_stats",
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "db_table": "popular_content",
                "ordering": ["timeframe", "rank"],
                "indexes": [
                    models.Index(
                        fields=["timeframe", "rank"], name="idx_popular_timeframe"
                    )
                ],
                "unique_together": {("blog", "timeframe")},
            },
        ),
    ]
