# Generated by Django 6.0.3 on 2026-03-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogview",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_records",
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="hourlyblogstat",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hourly_stats",
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="popularcontent",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="popularity_stats",
                to="blog.blog",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(fields=["-session_date"], name="idx_session_date"),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["ip_hash", "-session_date"], name="idx_session_visitor"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitorsession",
            unique_together={("ip_hash", "session_date")},
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(
                fields=["blog", "-viewed_at"], name="idx_view_blog_date"
            ),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["ip_hash", "blog"], name="idx_view_dedup"),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(
                fields=["utm_source", "utm_medium"], name="idx_view_utm"
            ),
        ),
        migrations.AddIndex(
            model_name="blogview",
            index=models.Index(fields=["-viewed_at"], name="idx_view_recent"),
        ),
        migrations.AddIndex(
            model_name="hourlyblogstat",
            index=models.Index(fields=["-hour"], name="idx_hourly_stat_hour"),
        ),
        migrations.AddIndex(
            model_name="hourlyblogstat",
            index=models.Index(fields=["blog", "-hour"], name="idx_hourly_blog_hour"),
        ),
        migrations.AlterUniqueTogether(
            name="hourlyblogstat",
            unique_together={("blog", "hour")},
        ),
        migrations.AddIndex(
            model_name="popularcontent",
            index=models.Index(
                fields=["timeframe", "rank"], name="idx_popular_timeframe"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="popularcontent",
            unique_together={("blog", "timeframe")},
        ),
    ]
